### ISSUE TITLE
OAuth is missing a hash_function

### ISSUE THREAD

**Issue by paulincai** [MichaelEPope/nsrestlet#1]
An encryption never takes place, consequently no authorization is returned

**Comment by MichaelEPope** [comment]
Hey Paul, can you post some more details, and some sample code (without your credentials)?  Then I can take a run at it on my own computer.

Thanks.

**Comment by MichaelEPope** [comment]
I am closing this (I need more details in order to any testing, sorry).  Feel free to post another issue if you want to discuss this further.

Thanks,
-Michael
