### ISSUE TITLE
Ask about custom script of invoiceLink

### ISSUE THREAD

**Issue by tho-can-code** [MichaelEPope/nsrestlet#6]
Hi @MichaelEPope, thank you so much for your library. If can would you please share me the source code of the demo in your screenshots? Thank you so much.

**Comment by MichaelEPope** [comment]
Hey @thosieucoi, I don't actually have any source code besides what is included in the readme (sorry :/).  If you grab the bit that is right under the 'Usage' section and the bit under the 'Recieving and Returning Data in the Restlet' section, it should work for general communication (the invoice link was just an example and such)

If your having some troubles, let me know, and I can see what's going on.

-Michael :)

**Comment by tho-can-code** [comment]
Thank you @MichaelEPope. I would like to get the invoices in PDF format, that's why I ask for the source code in demo.

**Comment by MichaelEPope** [comment]
@thosieucoi My code didn't do that, so you'd be on your own here, sorry :/.  But you could probably do that using some Suitescript (there is a function for making PDFs), and then by sending it to the file cabinet, and exposing it to the restlet somehow.

You might try asking about it on the Unofficial Slack Server (see there link at the bottom of the readme).  They can be pretty helpful on that sorta thing (especially if you give them some code you've already written and are running into troubles with).

**Comment by tho-can-code** [comment]
Thank you so much @MichaelEPope , I will try as your recommendation.
